version: "3.9"

services:
  frontend:
    container_name: ${FRONTEND_NAME}
    restart: always
    build:
      context: .
      dockerfile: .conf/production/frontend/Dockerfile
      args:
        ARG_VERSION: ${VERSION}
        ARG_API_URL: ${SERVER_PROTOCOL}://${SERVER_HOST}:${SERVER_PORT}/api/
    ports:
      - ${SERVER_PORT}:${FRONTEND_CONTAINER_PORT}
    environment:
      SERVER_HOST: ${SERVER_HOST}
      SERVER_PORT: ${SERVER_PORT}
      BACKEND_PROXY: ${BACKEND_NAME}:${BACKEND_PORT}
  backend:
    container_name: ${BACKEND_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./.conf/production/backend/Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      DEBUG: ${BACKEND_DEBUG}
      ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}
    depends_on:
      - db
  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - td_db:/var/lib/postgresql/data
volumes:
  td_db:
    name: td_db
