version: "3.9"

services:
  frontend:
    container_name: ${FRONTEND_NAME}
    restart: always
    build:
      context: .
      dockerfile: .conf/production/frontend/Dockerfile
      args:
        ARG_VERSION: ${VERSION}
        ARG_API_URL: ${SERVER_PROTOCOL}://${API_HOST}/
    ports:
      - ${SERVER_HTTP_PORT}:${FRONTEND_CONTAINER_HTTP_PORT}
      - ${SERVER_HTTPS_PORT}:${FRONTEND_CONTAINER_HTTPS_PORT}
    environment:
      CERTBOT_EMAIL: raphael.beekmann@gmail.com
      SERVER_HOST: ${SERVER_HOST}
      API_HOST: ${API_HOST}
      SERVER_HTTP_PORT: ${SERVER_HTTP_PORT}
      SERVER_HTTPS_PORT: ${SERVER_HTTPS_PORT}
      BACKEND_PROXY: ${BACKEND_NAME}:${BACKEND_PORT}
    volumes:
      - td_static_files:/vol/static
      - nginx-secret:/etc/letsencrypt
  backend:
    container_name: ${BACKEND_NAME}
    restart: always
    build:
      context: .
      dockerfile: ./.conf/production/backend/Dockerfile
    environment:
      BACKEND_PORT: ${BACKEND_PORT}
      SECRET_KEY: ${BACKEND_SECRET_KEY}
      DEBUG: ${BACKEND_DEBUG}
      ALLOWED_HOSTS: ${BACKEND_ALLOWED_HOSTS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${BACKEND_PORT}:${BACKEND_CONTAINER_PORT}
    volumes:
      - td_static_files:/vol/web
    depends_on:
      - db
  db:
    image: postgres:${DB_POSTGRES_VERSION}
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_CONTAINER_PORT}
    volumes:
      - td_db:/var/lib/postgresql/data
volumes:
  td_db:
    name: td_db
  td_static_files:
    name: td_static_files
  nginx-secret:
    name: nginx-secret
