openapi: 3.0.2
info:
  version: 1.0.0
  title: Tout Doux
  description: Organisation project
servers:
  - url: 'localhost:8000/api'
paths:
  /project:
    get:
      summary: Get all project
      responses:
        '200':
          description: Success