# Generated by Django 3.2.9 on 2022-02-20 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(limit_choices_to={'archived': False}, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tout_doux.project')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(editable=False, null=True)),
                ('collection', models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tout_doux.collection')),
                ('project', models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tout_doux.project')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tout_doux.section')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, choices=[('TH', 'Réfléchir'), ('WO', 'Travailler'), ('FI', 'Finir')], max_length=2, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('task', models.ForeignKey(blank=True, limit_choices_to={'completed': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='tout_doux.task')),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='dailytask',
            constraint=models.UniqueConstraint(fields=('date', 'task'), name='unique_task_for_date'),
        ),
    ]
