# Generated by Django 3.2.9 on 2022-11-23 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tout_doux', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('takes_whole_day', models.BooleanField(default=False)),
                ('project', models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True,
                                              on_delete=django.db.models.deletion.CASCADE, related_name='events',
                                              to='tout_doux.project')),
            ],
            options={
                'ordering': ('start_date', 'end_date'),
            },
        ),
    ]
