# Generated by Django 3.2.9 on 2023-02-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tout_doux', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_date', 'end_date', 'start_time', 'end_time')},
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'completed': False}, null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='daily_tasks',
                                    to='tout_doux.task'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='common_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='daily_tasks', to='tout_doux.commontask'),
        ),
        migrations.AddConstraint(
            model_name='dailytask',
            constraint=models.UniqueConstraint(fields=('date', 'common_task'), name='unique_common_task_for_date'),
        ),
        migrations.AddField(
            model_name='commontask',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='common_tasks', to='tout_doux.TaskTag'),
        ),

        migrations.AddField(
            model_name='dailytask',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='daily_tasks', to='tout_doux.TaskTag'),
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='tout_doux.ProjectTag'),
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='tout_doux.TaskTag'),
        ),
    ]
