# Generated by Django 3.2.9 on 2023-12-14 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import tout_doux.models.user
import tout_doux.utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0003_release_v0_3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=2000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='UserEmailChange',
            fields=[
                ('new_email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('expiry_date', models.DateTimeField(default=tout_doux.utils.date.now_plus_one_week, editable=False)),
            ],
            options={
                'db_table': 'tout_doux_user_email_change',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('date_joined',)},
        ),
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_name_for_type',
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='collections', related_query_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commontask',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='commontasks', related_query_name='commontasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='dailytasks', related_query_name='dailytasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='preferencess', related_query_name='preferencess', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collection',
            name='item_name',
            field=models.CharField(default='task', max_length=15),
        ),
        migrations.AlterField(
            model_name='commontask',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='commontask',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_for_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_name_for_user_and_type'),
        ),
        migrations.AddField(
            model_name='useremailchange',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='useremailchanges', related_query_name='useremailchanges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', related_query_name='feedbacks', to=settings.AUTH_USER_MODEL),
        ),
    ]
