# Generated by Django 3.2.9 on 2023-10-16 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0003_release_v0_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collections', related_query_name='collections', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commontask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commontasks', related_query_name='commontasks', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dailytasks', related_query_name='dailytasks', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events', related_query_name='events', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preferencess', related_query_name='preferencess', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', related_query_name='projects', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', related_query_name='sections', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tags', to='tout_doux.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', related_query_name='tasks', to='tout_doux.user'),
            preserve_default=False,
        ),
    ]
