# Generated by Django 3.2.9 on 2023-02-14 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0003_auto_20230213_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
