# Generated by Django 3.1.2 on 2021-03-19 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0004_auto_20210311_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
