# Generated by Django 3.2.9 on 2023-03-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tout_doux', '0004_auto_20230214_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('project', 'Project'), ('task', 'Task')], max_length=7)),
                ('name', models.CharField(max_length=20, unique=True)),
                ('color', models.CharField(max_length=7)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name', 'type'), name='unique_name_for_type'),
        ),
        migrations.AlterField(
            model_name='commontask',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'task'}, related_name='common_tasks',
                                         to='tout_doux.Tag'),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'task'}, related_name='daily_tasks',
                                         to='tout_doux.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'project'}, related_name='projects',
                                         to='tout_doux.Tag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, limit_choices_to={'type': 'task'}, related_name='tasks',
                                         to='tout_doux.Tag'),
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
        migrations.DeleteModel(
            name='TaskTag',
        ),
    ]
