# Generated by Django 6.1 on 2026-08-27 21:14

import django.db.models.deletion
import tout_doux.models.user
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tout_doux', '0005_alter_user_related_names')]

    dependencies = [
        ('tout_doux', '0004_release_v0_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commontask',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useremailchange',
            name='user',
            field=models.ForeignKey(default=tout_doux.models.user.get_anonymous_user, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', related_query_name='%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
    ]
