# Generated by Django 3.2.9 on 2023-10-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0005_auto_20231016_2250'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_name_for_type',
        ),
        migrations.AddConstraint(
            model_name='commontask',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_for_user'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name', 'type'), name='unique_name_for_user_and_type'),
        ),
    ]
