# Generated by Django 6.1 on 2026-08-27 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0006_release_v0_6'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-created_on', '-pk')},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_on', '-pk')},
        ),
    ]
