# Generated by Django 3.2.9 on 2023-10-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0006_auto_20231016_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commontask',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
