# Generated by Django 3.1.2 on 2021-03-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0006_auto_20210321_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, limit_choices_to={'archived': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tout_doux.project'),
        ),
    ]
