# Generated by Django 3.2.9 on 2023-03-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#37474F', 'Grey Dark'), ('#607D8B', 'Grey'), ('#880E4F', 'Pink Dark'), ('#9C27B0', 'Purple'), ('#673AB7', 'Purple Dark'), ('#3F51B5', 'Indigo'), ('#0D47A1', 'Dark Blue'), ('#2962FF', 'Blue'), ('#2196F3', 'Light Blue'), ('#00BCD4', 'Cyan'), ('#009688', 'Teal'), ('#4CAF50', 'Green'), ('#8BC34A', 'Light Green'), ('#9E9D24', 'Lime'), ('#FFB300', 'Yellow'), ('#FB8C00', 'Yellow Dark'), ('#FF5722', 'Orange'), ('#E53935', 'Red'), ('#B71C1C', 'Red Dark'), ('#794948', 'Brown')], max_length=7),
        ),
    ]
