# Generated by Django 6.1 on 2026-09-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0007_release_v0_6_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('pk',)},
        ),
    ]
