# Generated by Django 6.1 on 2026-09-09 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tout_doux', '0008_alter_tag_options'), ('tout_doux', '0009_alter_dailytask_date')]

    dependencies = [
        ('tout_doux', '0007_release_v0_6_1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
