# Generated by Django 3.2.9 on 2023-04-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0008_alter_tag_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
