# Generated by Django 6.1 on 2026-09-22 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0008_release_v0_7'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
