# Generated by Django 6.1 on 2026-09-05 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0008_alter_tag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
