# Generated by Django 3.2.9 on 2023-04-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0009_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_wheel_mode', models.CharField(choices=[('number', 'Number'), ('percent', 'Percent')], default='number', max_length=10)),
            ],
        ),
    ]
