# Generated by Django 3.2.9 on 2023-04-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0010_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='item_name',
            field=models.CharField(default='task', max_length=15),
        ),
    ]
