# Generated by Django 3.2.9 on 2023-04-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0011_collection_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='item_name',
            field=models.CharField(blank=True, default='task', max_length=15),
        ),
    ]
