# Generated by Django 3.1.2 on 2021-03-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0011_task_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='List',
            new_name='Collection',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='list',
            new_name='collection',
        ),
    ]
