# Generated by Django 3.1.2 on 2021-03-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0013_dailytask'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dailytask',
            constraint=models.UniqueConstraint(fields=('date', 'task'), name='unique_task_for_date'),
        ),
    ]
