# Generated by Django 3.2.9 on 2023-04-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0015_alter_task_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Preferences',
        ),
    ]
