# Generated by Django 3.1.2 on 2021-05-27 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0015_auto_20210525_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project', models.ForeignKey(limit_choices_to={'archived': False}, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tout_doux.project')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tout_doux.section'),
        ),
    ]
