# Generated by Django 3.2.9 on 2023-11-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0015_auto_20231112_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('current_email', models.EmailField(max_length=100)),
                ('new_email', models.EmailField(max_length=100)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
    ]
