# Generated by Django 3.2.9 on 2023-11-12 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0016_useremailchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailchange',
            name='id',
        ),
        migrations.AlterField(
            model_name='useremailchange',
            name='token',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='useremailchange',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
