# Generated by Django 3.2.9 on 2021-11-28 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0016_auto_20210527_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='task',
            field=models.ForeignKey(blank=True, limit_choices_to={'completed': False}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='tout_doux.task'),
        ),
    ]
