# Generated by Django 3.2.9 on 2023-11-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0017_auto_20231112_0133'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useremailchange',
            table='user_email_change',
        ),
    ]
