# Generated by Django 3.2.9 on 2023-11-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0018_alter_useremailchange_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useremailchange',
            table='tout_doux_user_email_change',
        ),
    ]
