# Generated by Django 3.2.9 on 2023-11-12 00:53

from django.db import migrations, models
import tout_doux.utils.date


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0019_alter_useremailchange_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailchange',
            name='expiry_date',
            field=models.DateTimeField(default=tout_doux.utils.date.now_plus_one_week, editable=False),
        ),
    ]
