# Generated by Django 3.2.9 on 2023-11-13 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0020_useremailchange_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailchange',
            name='current_email',
        ),
        migrations.RemoveField(
            model_name='useremailchange',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useremailchange',
            name='user',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='useremailchanges', related_query_name='useremailchanges', to='tout_doux.user'),
            preserve_default=False,
        ),
    ]
