# Generated by Django 3.2.9 on 2023-12-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tout_doux', '0025_alter_feedback_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='item_name',
            field=models.CharField(default='task', max_length=15),
        ),
    ]
