export const apiRoutes = {
    project: 'project/',
    projectDetailed: 'project/detailed/',
    projectById: 'project/:projectId/',
    section: 'section/',
    sectionById: 'section/:sectionId/',
    task: 'task/',
    taskById: 'task/:taskId/',
    event: 'event/',
    eventById: 'event/:eventId/',
    collection: 'collection/',
    collectionDetailed: 'collection/detailed',
    collectionById: 'collection/:collectionId/',
    dailyTask: 'daily-task/',
    dailyTaskSummary: 'daily-task/summary/',
    dailyTaskById: 'daily-task/:dailyTaskId/',
    tag: 'tag/',
    tagUnique: 'tag/is-name-unique/',
    tagById: 'tag/:id/',
    commonTask: 'common-task/',
    commonTaskUnique: 'common-task/is-name-unique/',
    commonTaskById: 'common-task/:id/',
}
