export const apiRoutes = {
    project: 'project/',
    projectDetailed: 'project/detailed/',
    projectById: 'project/:projectId/',
    projectSections: 'project/:projectId/sections/',
    section: 'section/',
    sectionById: 'section/:sectionId/',
    task: 'task/',
    taskById: 'task/:taskId/',
    event: 'event/',
    eventById: 'event/:eventId/',
    collection: 'collection/',
    collectionDetailed: 'collection/detailed',
    collectionById: 'collection/:collectionId/',
    dailyTask: 'daily-task/',
    dailyTaskSummary: 'daily-task/summary/',
    dailyTaskById: 'daily-task/:dailyTaskId/',
}
